=== DaoTrungTin2005/XML/Trainning/Buổi 5 Câu 2/sinhvien.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="DanhSachSinhVien">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SinhVien" type="SinhVienType" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="SinhVienType">
        <xs:sequence>
            <xs:element name="HoTen" type="xs:string"></xs:element>
            <xs:element name="Lop" type="LopType"></xs:element>
            <xs:element name="DanhsachMonHoc" type="DanhSachMonHocType"></xs:element>
        </xs:sequence>
        <xs:attribute name="MSSV" type="MSSVType"></xs:attribute>
    </xs:complexType>

    <xs:simpleType name="LopType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TBK50DH"></xs:enumeration>
            <xs:enumeration value="TBK50CD"></xs:enumeration>
            <xs:enumeration value="TBK51DH"></xs:enumeration>
            <xs:enumeration value="TBK51CD"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MSSVType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="DanhSachMonHocType">
        <xs:sequence>
            <xs:element name="MonHoc" type="MonHocType" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MonHocType">
        <xs:sequence>
            <xs:element name="TenMonHoc" type="xs:string"></xs:element>
            <xs:element name="TinChi" type="TinChiType"></xs:element>
            <xs:element name="DiemMonHoc" type="DiemMonHocType"></xs:element>
        </xs:sequence>
        <xs:attribute name="MaMon" type="MaMonType"></xs:attribute>
    </xs:complexType>

    <xs:simpleType name="TinChiType">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"></xs:minInclusive>
            <xs:maxInclusive value="5"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MaMonType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z]{2}\d{2}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DiemMonHocType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"></xs:minInclusive>
            <xs:maxInclusive value="10"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== DaoTrungTin2005/XML/Trainning/Buổi 5 Câu 2/sinhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="sinhvien.xsl" type="text/xsl"?>
<DanhSachSinhVien
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="sinhvien.xsd">
    
    <SinhVien>
        <HoTen>Nguyễn Hoàng Thuận</HoTen>
        <Lop>TBK50CD</Lop>
        <DanhsachMonHoc>
            <MonHoc MaMon="IT01">
                <TenMonHoc>Tiếng Anh</TenMonHoc>
                <TinChi>4</TinChi>
                <DiemMonHoc>10</DiemMonHoc>
            </MonHoc>

            <MonHoc MaMon="PT01">
                <TenMonHoc>Toán</TenMonHoc>
                <TinChi>4</TinChi>
                <DiemMonHoc>9</DiemMonHoc>
            </MonHoc>
        </DanhsachMonHoc>
    </SinhVien>

    <SinhVien>
        <HoTen>Huỳnh Kiến Quốc</HoTen>
        <Lop>TBK51CD</Lop>
        <DanhsachMonHoc>
            <MonHoc MaMon="IT01">
                <TenMonHoc>Ngữ Văn</TenMonHoc>
                <TinChi>4</TinChi>
                <DiemMonHoc>0</DiemMonHoc>
            </MonHoc>

            <MonHoc MaMon="PT01">
                <TenMonHoc>Tiếng Anh</TenMonHoc>
                <TinChi>4</TinChi>
                <DiemMonHoc>0</DiemMonHoc>
            </MonHoc>
        </DanhsachMonHoc>
    </SinhVien>

</DanhSachSinhVien>
