=== DaoTrungTin2005/XML/Trainning/Giữa Kì/vaccine.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="DanhSachKhachHang">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="KhachHang" type="KhachHangType" minOccurs="1" maxOccurs="unbounded"></xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="UniqueSoDienThoai">
            <xs:selector xpath="KhachHang"></xs:selector>
            <xs:field xpath="SoDienThoai"></xs:field>
        </xs:unique>

    </xs:element>

    <xs:complexType name="KhachHangType">
        <xs:sequence>
            <xs:element name="TenKhachHang" type="xs:string"></xs:element>
            <xs:element name="SoDienThoai" type="SoDienThoaiType"></xs:element>
            <xs:element name="DanhSachConCuaKhachHang" type="DanhSachConCuaKhachHangType"></xs:element>
            <xs:element name="DanhSachVaccine" type="DanhSachVaccineType"></xs:element>
        </xs:sequence>
        <xs:attribute name="MaKhachHang" type="MaKhachHangType"></xs:attribute>
    </xs:complexType>

    <xs:simpleType name="SoDienThoaiType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{10}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="MaKhachHangType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z]{2}\d{2}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="DanhSachVaccineType">
        <xs:sequence>
            <xs:element name="Vaccine" type="VaccineType" minOccurs="1" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VaccineType">
        <xs:sequence>
            <xs:element name="TenVaccine" type="xs:string"></xs:element>
            <xs:element name="NgayTiem" type="xs:date"></xs:element>
            <xs:element name="NgayTiemTiepTheo" type="xs:date"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DanhSachConCuaKhachHangType">
        <xs:sequence>
            <xs:element name="ConKhachHang" type="ConKhachHangType" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ConKhachHangType">
        <xs:sequence>
            <xs:element name="TenCon" type="TenConType"></xs:element>
            <xs:element name="DanhSachVaccineCuaCon" type="DanhSachVaccineCuaConType"></xs:element>

        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DanhSachVaccineCuaConType">
        <xs:sequence>
            <xs:element name="VaccineCuaCon" type="VaccineCuaConType" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="VaccineCuaConType">
        <xs:sequence>
            <xs:element name="TenVaccine" type="TenVaccineType"></xs:element>
            <xs:element name="NgayTiem" type="xs:date"></xs:element>
            <xs:element name="NgayTiemTiepTheo" type="xs:date"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="TenConType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"></xs:maxLength>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TenVaccineType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Sởi"></xs:enumeration>
            <xs:enumeration value="Cảm Cúm"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== DaoTrungTin2005/XML/Trainning/Giữa Kì/vaccine.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="vaccine.xsl" type="text/xsl"?>
<DanhSachKhachHang
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="vaccine.xsd">
    
    <KhachHang MaKhachHang="Ab01">
        <TenKhachHang>Đào Trung Tín</TenKhachHang>
        <SoDienThoai>0326751251</SoDienThoai>
        <DanhSachConCuaKhachHang>
            <ConKhachHang>
                <TenCon>Lê Thành Đạt</TenCon>
                <DanhSachVaccineCuaCon>
                    <VaccineCuaCon>
                        <TenVaccine>Sởi</TenVaccine>
                        <NgayTiem>2005-08-01</NgayTiem>
                        <NgayTiemTiepTheo>2005-09-01</NgayTiemTiepTheo>
                    </VaccineCuaCon>

                    <VaccineCuaCon>
                        <TenVaccine>Cảm Cúm</TenVaccine>
                        <NgayTiem>2006-08-01</NgayTiem>
                        <NgayTiemTiepTheo>2006-09-01</NgayTiemTiepTheo>
                    </VaccineCuaCon>
                </DanhSachVaccineCuaCon>
            </ConKhachHang>

            <ConKhachHang>
                <TenCon>Lê Thành Công</TenCon>
                <DanhSachVaccineCuaCon>
                    <VaccineCuaCon>
                        <TenVaccine>Sởi</TenVaccine>
                        <NgayTiem>2005-08-01</NgayTiem>
                        <NgayTiemTiepTheo>2005-09-01</NgayTiemTiepTheo>
                    </VaccineCuaCon>

                    <VaccineCuaCon>
                        <TenVaccine>Cảm Cúm</TenVaccine>
                        <NgayTiem>2006-08-01</NgayTiem>
                        <NgayTiemTiepTheo>2006-09-01</NgayTiemTiepTheo>
                    </VaccineCuaCon>
                </DanhSachVaccineCuaCon>
            </ConKhachHang>
        </DanhSachConCuaKhachHang>

        <DanhSachVaccine>
            <Vaccine>
                <TenVaccine>Covid</TenVaccine>
                <NgayTiem>2025-08-01</NgayTiem>
                <NgayTiemTiepTheo>2006-09-01</NgayTiemTiepTheo>
            </Vaccine>

            <Vaccine>
                <TenVaccine>Epula</TenVaccine>
                <NgayTiem>2095-08-01</NgayTiem>
                <NgayTiemTiepTheo>2006-09-01</NgayTiemTiepTheo>
            </Vaccine>
        </DanhSachVaccine>
    </KhachHang>




    <KhachHang MaKhachHang="Ab02">
        <TenKhachHang>Như</TenKhachHang>
        <SoDienThoai>0326751250</SoDienThoai>
        <DanhSachConCuaKhachHang>
            <ConKhachHang>
                <TenCon>Lê Thành Đạt</TenCon>
                <DanhSachVaccineCuaCon>
                    <VaccineCuaCon>
                        <TenVaccine>Sởi</TenVaccine>
                        <NgayTiem>2005-08-01</NgayTiem>
                        <NgayTiemTiepTheo>2005-09-01</NgayTiemTiepTheo>
                    </VaccineCuaCon>

                    <VaccineCuaCon>
                        <TenVaccine>Cảm Cúm</TenVaccine>
                        <NgayTiem>2006-08-01</NgayTiem>
                        <NgayTiemTiepTheo>2006-09-01</NgayTiemTiepTheo>
                    </VaccineCuaCon>
                </DanhSachVaccineCuaCon>
            </ConKhachHang>

            <ConKhachHang>
                <TenCon>Lê Thành Công</TenCon>
                <DanhSachVaccineCuaCon>
                    <VaccineCuaCon>
                        <TenVaccine>Sởi</TenVaccine>
                        <NgayTiem>2005-08-01</NgayTiem>
                        <NgayTiemTiepTheo>2005-09-01</NgayTiemTiepTheo>
                    </VaccineCuaCon>

                    <VaccineCuaCon>
                        <TenVaccine>Cảm Cúm</TenVaccine>
                        <NgayTiem>2006-08-01</NgayTiem>
                        <NgayTiemTiepTheo>2006-09-01</NgayTiemTiepTheo>
                    </VaccineCuaCon>
                </DanhSachVaccineCuaCon>
            </ConKhachHang>
        </DanhSachConCuaKhachHang>

        <DanhSachVaccine>
            <Vaccine>
                <TenVaccine>Covid</TenVaccine>
                <NgayTiem>2005-08-01</NgayTiem>
                <NgayTiemTiepTheo>2006-09-01</NgayTiemTiepTheo>
            </Vaccine>

            <Vaccine>
                <TenVaccine>Epula</TenVaccine>
                <NgayTiem>2005-08-01</NgayTiem>
                <NgayTiemTiepTheo>2006-09-01</NgayTiemTiepTheo>
            </Vaccine>
        </DanhSachVaccine>
    </KhachHang>



</DanhSachKhachHang>
