=== DaoTrungTin2005/XML/Buoi4/Cau1/sinhvien.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="DanhSachSinhVien">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="SinhVien" type="SinhVienType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="SinhVienType">
        <xs:sequence>
            <xs:element name="HoTen" type= "HoTenType"></xs:element>
            <xs:element name="Tuoi" type="TuoiType"/>
            <xs:element name="Lop" type="xs:string" minOccurs="1"/>
        </xs:sequence>

            <xs:attribute name="MaSV" type="MaSVType" use="required"/>
    </xs:complexType>

    <!-- MaSV: bắt đầu SV + đủ 8 ký tự -->
    <xs:simpleType name="MaSVType">
        <xs:restriction base="xs:string">
            <xs:length value="8"/>
            <xs:pattern value="SV\d{6}"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- HoTen: tối đa 50 ký tự -->
    <xs:simpleType name="HoTenType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Tuoi: từ 18 → 30 -->
    <xs:simpleType name="TuoiType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="18"/>
            <xs:maxInclusive value="30"/>
        </xs:restriction>
    </xs:simpleType>



</xs:schema>

=== DaoTrungTin2005/XML/Buoi4/Cau1/sinhvien_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>

<DanhSachSinhVien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="sinhvien.xsd">

    <SinhVien MaSV="SV000001">
        <HoTen>Nguyen Van A</HoTen>
        <Tuoi>20</Tuoi>
        <Lop>CTK42</Lop>
    </SinhVien>

    <SinhVien MaSV="SV000002">
        <HoTen>Tran Thi B</HoTen>
        <Tuoi>22</Tuoi>
        <Lop>CTK43</Lop>
    </SinhVien>

</DanhSachSinhVien>
