=== DaoTrungTin2005/XML/Buoi4/Cau1/sinhvien.dtd
<!ELEMENT DanhSachSinhVien (SinhVien+)>

<!ELEMENT SinhVien (HoTen, Tuoi, Lop)>
<!ATTLIST SinhVien MaSV ID #REQUIRED>

<!ELEMENT HoTen (#PCDATA)>
<!ELEMENT Tuoi (#PCDATA)>
<!ELEMENT Lop (#PCDATA)>

=== DaoTrungTin2005/XML/Buoi4/Cau1/sinhvien_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE DanhSachSinhVien SYSTEM "sinhvien.dtd">

<DanhSachSinhVien>
    <SinhVien MaSV="SV001">
        <HoTen>Nguyen Van A</HoTen>
        <Tuoi>20</Tuoi>
        <Lop>CTK42</Lop>
    </SinhVien>

    <SinhVien MaSV="SV002">
        <HoTen>Tran Thi B</HoTen>
        <Tuoi>82</Tuoi>
        <Lop>CTK43</Lop>
    </SinhVien>
</DanhSachSinhVien>
