=== DaoTrungTin2005/XML/Bai1/Nhansu.dtd
<!ELEMENT CongTy (TenCongTy, DiaChi, ChiNhanh+)>

<!ELEMENT TenCongTy (#PCDATA)>

<!ELEMENT DiaChi (SoNha, Duong, Quan, ThanhPho)>
<!ELEMENT SoNha (#PCDATA)>
<!ELEMENT Duong (#PCDATA)>
<!ELEMENT Quan (#PCDATA)>
<!ELEMENT ThanhPho (#PCDATA)>

<!ELEMENT ChiNhanh (TenChiNhanh, DiaDiem, NhanVien+)>
<!ELEMENT TenChiNhanh (#PCDATA)>
<!ELEMENT DiaDiem (#PCDATA)>

<!ELEMENT NhanVien (BangCap, HoTen, DienThoai, Email)>
<!ATTLIST NhanVien quanly (true | false) #REQUIRED>

<!ELEMENT BangCap (#PCDATA)>
<!ELEMENT HoTen (#PCDATA)>
<!ELEMENT DienThoai (#PCDATA)>
<!ELEMENT Email (#PCDATA)>

=== DaoTrungTin2005/XML/Bai1/Nhansu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CongTy SYSTEM "Nhansu.dtd">

<CongTy>
    <TenCongTy>Dat Company</TenCongTy>

    <DiaChi>
        <SoNha>54/24A</SoNha>
        <Duong>Mau Than</Duong>
        <Quan>Quan 5</Quan>
        <ThanhPho>TP. HCM</ThanhPho>
    </DiaChi>

    <!-- Chi nhanh 1 -->
    <ChiNhanh>
        <TenChiNhanh>abc</TenChiNhanh>

        <DiaDiem>kkk</DiaDiem>

        <NhanVien quanly="true">
           <BangCap>thacsi</BangCap>
            <HoTen>dat</HoTen>
            <DienThoai>113</DienThoai>
            <Email>g@</Email>
        </NhanVien>

        <NhanVien quanly="false">
           <BangCap>thacsi</BangCap>
            <HoTen>tin</HoTen>
            <DienThoai>113</DienThoai>
            <Email>g@</Email>
        </NhanVien>

        <NhanVien quanly="false">
           <BangCap>thacsi</BangCap>
            <HoTen>huan</HoTen>
            <DienThoai>113</DienThoai>
            <Email>g@</Email>
        </NhanVien>
        
    </ChiNhanh>

    <!-- Chi nhanh 2 -->
    <ChiNhanh>
        <TenChiNhanh>abc</TenChiNhanh>

        <DiaDiem>kkk</DiaDiem>

        <NhanVien quanly="true">
           <BangCap>thacsi</BangCap>
            <HoTen>dat</HoTen>
            <DienThoai>113</DienThoai>
            <Email>g@</Email>
        </NhanVien>

        <NhanVien quanly="false">
           <BangCap>thacsi</BangCap>
            <HoTen>tin</HoTen>
            <DienThoai>113</DienThoai>
            <Email>g@</Email>
        </NhanVien>

        <NhanVien quanly="false">
           <BangCap>thacsi</BangCap>
            <HoTen>huan</HoTen>
            <DienThoai>113</DienThoai>
            <Email>g@</Email>
        </NhanVien>
        
    </ChiNhanh>

</CongTy>
