=== DaoTrungTin2005/XML/Buoi3/Cau1/matches.dtd
<!ELEMENT matches (match+)>

<!ELEMENT match (score, teams, events)>

<!ELEMENT score (#PCDATA)>

<!ELEMENT teams (home, away)>
<!ELEMENT home (#PCDATA)>
<!ELEMENT away (#PCDATA)>

<!ELEMENT events (event+)>
<!ELEMENT event (minute, player, team?)>

<!ATTLIST event type (goal | yellow | red) #REQUIRED
                penalty (yes | no) "no"
>

<!ELEMENT minute (#PCDATA)>
<!ELEMENT player (#PCDATA)>
<!ELEMENT team (#PCDATA)>

=== DaoTrungTin2005/XML/Buoi3/Cau1/matches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE matches SYSTEM "matches.dtd">

<matches>
    <match>
        <score>1-2</score>

        <teams>
            <home>MC</home>
            <away>BC</away>
        </teams>

        <events>
            <event type="goal" penalty="yes">
                <minute>16</minute>
                <player>Luis Suarez</player>
                <team>Barcelona</team>
            </event>

            <event type="goal" penalty="no">
                <minute>30</minute>
                <player>Luis Suarez</player>
                <team>Barcelona</team>
            </event>

            <event type="yellow">
                <minute>41</minute>
                <player>Ivan Rakitic</player>
                <team>Barcelona</team>
            </event>

            <event type="red">
                <minute>74</minute>
                <player>Gael Clichy</player>
                <team>Manchester City</team>
            </event>

        </events>
    </match>
</matches>
